# -*- coding: utf-8 -*-
"""PANDASTUT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DmLtDq-oJxwtwojmCtt3M60AxdZ34umh

LOADING DATAFRAMES
"""

import pandas as pd
coffee =pd.read_csv("coffee.csv")

coffee.head()

results=pd.read_parquet("results.parquet")
bios=pd.read_csv("bios.csv")

bios.to_excel("data.xlsx", index=False)
bios.head()

"""ACCESSING DATAFRAMES"""

coffee

display(coffee)

coffee.sample(10) #used for random values

"""ACCESSING DATA WITH PANDAS"""

coffee.loc[2:]          #passing rows and cloumns to access specific data
coffee.loc[[1,2,7]]

coffee.loc[1,"Units Sold"]=10

coffee

coffee.at[1,"Units Sold"]

coffee.sort_values("Units Sold")#sorts in ascending oreder for descending make ascending =false